diyabet/diyabet/Controllers/DefaultController.cs
using diyabet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace diyabet.Controllers
{   
    public class DefaultController : Controller
    {
        DiyabetDB context = new DiyabetDB();
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GirisYap(string kullaniciAdi, string parola)
        {
            Uyeler uye = context.Uyeler.FirstOrDefault(x => x.KullaniciAdi == kullaniciAdi);
            if (uye.Sifre == parola)
            {
                HttpCookie kulCookie = new HttpCookie("uye");
                kulCookie["ID"] = uye.UyeID.ToString();
                kulCookie["KullaniciAdi"] = uye.KullaniciAdi;
                kulCookie.Expires = DateTime.Now.AddMinutes(Session.Timeout);
                Response.Cookies.Add(kulCookie);
                kulCookie["uyeTipi"] = uye.UyeTipi.ToString();
                if (uye.UyeTipi == 0)
                    return RedirectToAction("Index", "Admin");
                else if (uye.UyeTipi == 1)
                    return RedirectToAction("Index", "Home");
                else if (uye.UyeTipi == 2)
                    return RedirectToAction("Index", "Doktor");
            }
            else
                ViewBag.Mesaj = "Kullanıcı Adı veya parola yanlış";
            return View();
        }

        public ActionResult KayitOl()
        {
            return View();
        }

       [HttpPost]
        public ActionResult KayitOl(Hasta yeniHasta, string Sifre, string SifreTekrar, string KullaniciAdi, string AdiSoyadi, string Mail)
        {
            Uyeler yeniUye = new Uyeler();
            if (Sifre == SifreTekrar)
            {
                yeniUye.UyeTipi         = 1;
                yeniUye.AdiSoyadi       = AdiSoyadi;
                yeniUye.Sifre           = Sifre;
                yeniUye.KullaniciAdi    = KullaniciAdi;
                yeniUye.Mail            = Mail;
                context.Uyeler.Add(yeniUye);
                context.SaveChanges();
                yeniHasta.UyeID = yeniUye.UyeID;
                yeniHasta.Uyeler = yeniUye;
                context.Hasta.Add(yeniHasta);
                
                context.Uyeler.Add(yeniUye);
                context.SaveChanges();
                return RedirectToAction("Index", "Home", new { });
            }
            else
            {
                ViewBag.Message = "Şifreler uyuşmuyor.";
                return View();
            }
        }
    }
}

diyabet/diyabet/Views/Default/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/css/style.css" rel="stylesheet" />
</head>
<body class="login">
    <div class="head">Giriş Yap</div>
    <div class="content">
        <div class="loginContent">
            @using (Html.BeginForm("GirisYap", "Default"))
            {
            <div class="row">
                <div class="left">Kullanıcı Adı</div>@ViewBag.Mesaj
                <div class="right">@Html.TextBox("kullaniciAdi", null, new { required = "required" })</div>
                <div class="clear"></div>
            </div>
            <div class="row">
                <div class="left">Şifre</div>
                <div class="right">@Html.Password("parola", null, new { required = "required"})</div>
                <div class="clear"></div>
            </div>
            <div class="row">
                <div class="left"><input type="submit" value="Giriş Yap" class="button" /></div>
                <div class="right">@Html.ActionLink("Kayıt Ol", "KayitOl", new { }, new { @class = "button"})</div>
                <div class="clear"></div>
            </div>
            }
        </div>
    </div>
</body>
</html>

diyabet/diyabet/Views/Default/KayitOl.cshtml
@{
    ViewBag.Title = "KayitOl";
    Layout = "~/Views/AdminLayout.cshtml";
}
@using (Html.BeginForm("KayitOl", "Default"))
{
    @ViewBag.Message
<div class="kayitOl">
    <div class="left">
        <div class="row">
            <div class="leftContent">TC Kimlik Numarası</div>
            <div class="rightContent">@Html.TextBox("TCNo", null, new { required = "required", maxlength = "11", minlength = "11" })</div>
            <div class="clear"></div>
        </div>
        <div class="row">
            <div class="leftContent">Adı Soyadı</div>
            <div class="rightContent">@Html.TextBox("AdiSoyadi", null, new { required = "required" })</div>
            <div class="clear"></div>
        </div>
        <div class="row">
            <div class="leftContent">Doğum Tarihi</div>
            <div class="rightContent">@Html.TextBox("DogumTarihi", null, new { type = "date", required = "required" })</div>
            <div class="clear"></div>
        </div>
        <div class="row">
            <div class="leftContent">Telefon Numarası</div>
            <div class="rightContent">@Html.TextBox("TelefonNo", null, new { maxlength = "10", required = "required" })</div>
            <div class="clear"></div>
        </div>
        <div class="row">
            <div class="leftContent">Ev Adresi</div>
            <div class="rightContent">@Html.TextArea("Adres", new { required = "required" })</div>
            <div class="clear"></div>
        </div>
        <div class="row">
            <div class="rightContent"><input type="submit" value="Kayıt Ol" class="button"/></div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="right">
        <div class="row">
            <div class="leftContent">Kullanıcı Adı</div>
            <div class="rightContent">@Html.TextBox("KullaniciAdi", null, new { required = "required" })</div>
            <div class="clear"></div>
        </div>
        <div class="row">
            <div class="leftContent">Mail Adresi</div>
            <div class="rightContent">@Html.TextBox("Mail", null, new { required = "required" })</div>
            <div class="clear"></div>
        </div>
        <div class="row">
            <div class="leftContent">Şifre</div>
            <div class="rightContent">@Html.Password("Sifre", null, new { required = "required" })</div>
            <div class="clear"></div>
        </div>
        <div class="row">
            <div class="leftContent">Şifre (Tekrar)</div>
            <div class="rightContent">@Html.Password("SifreTekrar", null, new { required = "required" })</div>
            <div class="clear"></div>
        </div>
        <div class="row">
            @Html.CheckBox("chkYakin")Yakınıma bilgi verilmesini istiyorum.
            <div class="clear"></div>
        </div>
        <div id="yakinBilgileri">
            <div class="row">
                <div class="leftContent title">Hasta Yakınının</div>
                <div class="clear"></div>
            </div>
            <div class="row">
                <div class="leftContent">Adı</div>
                <div class="rightContent">@Html.TextBox("YakinAdSoyad")</div>
                <div class="clear"></div>
            </div>
            <div class="row">
                <div class="leftContent">Yakınlık Derecesi</div>
                <div class="rightContent">@Html.TextBox("YakinlikDerecesi")</div>
                <div class="clear"></div>
            </div>
            <div class="row">
                <div class="leftContent">Mail Adresi</div>
                <div class="rightContent">@Html.TextBox("YakinMailAdresi", null, new { type = "email" })</div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
}